import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { copyFileSync, mkdtempSync, mkdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const root = fileURLToPath(new URL("../", import.meta.url));
const run = (command, args, cwd = root) => execFileSync(command, args, { cwd, stdio: "inherit" });
const output = resolve(root, "dist/release");
mkdirSync(output, { recursive: true });
run("npm", ["run", "build"]);
run("npm", ["test"]);
const manifests = [];
for (const directory of ["hcp-protocol", "hcp-sdk", "hcp-runner"]) {
  const cwd = join(root, "packages", directory);
  const [packed] = JSON.parse(execFileSync("npm", ["pack", "--json", "--pack-destination", output], { cwd, encoding: "utf8" }));
  assert.ok(packed.files.some(file => file.path === "LICENSE"));
  assert.ok(packed.files.some(file => file.path === "README.md"));
  assert.ok(!packed.files.some(file => /\.test\.|^src\//.test(file.path)));
  manifests.push({ name: packed.name, version: packed.version, filename: packed.filename,
    sha256: createHash("sha256").update(readFileSync(join(output, packed.filename))).digest("hex") });
}
assert.equal(new Set(manifests.map(pkg => pkg.version)).size, 1);
const consumer = mkdtempSync(join(tmpdir(), "hcp-package-consumer-"));
try {
  writeFileSync(join(consumer, "package.json"), JSON.stringify({ private: true, type: "module" }));
  run("npm", ["install", "--ignore-scripts", "--no-audit", "--no-fund", ...manifests.map(pkg => join(output, pkg.filename)), "ws@^8.21.0", "typescript@^5.6.0", "@types/node@^22.0.0"], consumer);
  run(join(consumer, "node_modules/.bin/hcp-runner"), ["version"], consumer);
  run(process.execPath, ["--input-type=module", "-e", `
    import assert from 'node:assert/strict';
    import {readFileSync} from 'node:fs';
    import {createMcpReviewContract} from '@harness-control/protocol';
    import {createHcpMessageJsonSchema} from '@harness-control/protocol/json-schema';
    const read = name => JSON.parse(readFileSync(new URL(import.meta.resolve(name)), 'utf8'));
    assert.deepEqual(read('@harness-control/protocol/mcp-review.json'), createMcpReviewContract());
    assert.deepEqual(read('@harness-control/protocol/schema.json'), createHcpMessageJsonSchema());
    console.log('Packaged JSON contracts match public runtime schema factories');
  `], consumer);
  run(process.execPath, ["--input-type=module", "-e", "await import('@harness-control/runner/accounts'); await import('@harness-control/runner'); await import('@harness-control/runner/pairing'); await import('@harness-control/protocol/json-schema'); await import('@harness-control/protocol/conformance'); console.log('Public exports imported without CLI side effects')"], consumer);
  copyFileSync(join(root, "examples/custom-harness.ts"), join(consumer, "custom-harness.ts"));
  copyFileSync(join(root, "examples/conversation-controls.ts"), join(consumer, "conversation-controls.ts"));
  run(join(consumer, "node_modules/.bin/tsc"), ["--strict", "--skipLibCheck", "--module", "NodeNext", "--target", "ES2022", "custom-harness.ts", "conversation-controls.ts"], consumer);
  copyFileSync(join(root, "examples/public-sdk.mjs"), join(consumer, "example.mjs"));
  run(process.execPath, ["example.mjs"], consumer);
  copyFileSync(join(root, "examples/conversation-controls-consumer.mjs"), join(consumer, "conversation-controls-consumer.mjs"));
  run(process.execPath, ["conversation-controls-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/native-session-ownership-consumer.mjs"), join(consumer, "native-session-ownership-consumer.mjs"));
  run(process.execPath, ["native-session-ownership-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/native-proposal-input-consumer.mjs"), join(consumer, "native-proposal-input-consumer.mjs"));
  run(process.execPath, ["native-proposal-input-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/rejection-feedback-consumer.mjs"), join(consumer, "rejection-feedback-consumer.mjs"));
  run(process.execPath, ["rejection-feedback-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/proposed-plan-content-consumer.mjs"), join(consumer, "proposed-plan-content-consumer.mjs"));
  run(process.execPath, ["proposed-plan-content-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/native-plan-observations-consumer.mjs"), join(consumer, "native-plan-observations-consumer.mjs"));
  run(process.execPath, ["native-plan-observations-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/portable-items-consumer.mjs"), join(consumer, "portable-items-consumer.mjs"));
  run(process.execPath, ["portable-items-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/final-text-consumer.mjs"), join(consumer, "final-text-consumer.mjs"));
  run(process.execPath, ["final-text-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/input-files-consumer.mjs"), join(consumer, "input-files-consumer.mjs"));
  run(process.execPath, ["input-files-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/large-files-consumer.mjs"), join(consumer, "large-files-consumer.mjs"));
  run(process.execPath, ["large-files-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/history-media-consumer.mjs"), join(consumer, "history-media-consumer.mjs"));
  run(process.execPath, ["history-media-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/owned-images-consumer.mjs"), join(consumer, "owned-images-consumer.mjs"));
  run(process.execPath, ["owned-images-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/text-content-consumer.mjs"), join(consumer, "text-content-consumer.mjs"));
  run(process.execPath, ["text-content-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/reasoning-content-consumer.mjs"), join(consumer, "reasoning-content-consumer.mjs"));
  run(process.execPath, ["reasoning-content-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/native-goal-consumer.mjs"), join(consumer, "native-goal-consumer.mjs"));
  run(process.execPath, ["native-goal-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/native-child-consumer.mjs"), join(consumer, "native-child-consumer.mjs"));
  run(process.execPath, ["native-child-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/mcp-review-consumer.mjs"), join(consumer, "mcp-review-consumer.mjs"));
  run(process.execPath, ["mcp-review-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/mcp-proxy-consumer.mjs"), join(consumer, "mcp-proxy-consumer.mjs"));
  run(process.execPath, ["mcp-proxy-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/mcp-detach-consumer.mjs"), join(consumer, "mcp-detach-consumer.mjs"));
  run(process.execPath, ["mcp-detach-consumer.mjs"], consumer);
  copyFileSync(join(root, "examples/startup-cleanup-consumer.mjs"), join(consumer, "startup-cleanup-consumer.mjs"));
  run(process.execPath, ["startup-cleanup-consumer.mjs"], consumer);
  writeFileSync(join(output, "manifest.json"), JSON.stringify({ packages: manifests }, null, 2) + "\n");
  console.log(`Validated release artifacts: ${output}`);
} finally { rmSync(consumer, { recursive: true, force: true }); }
